xcassets:
    inputs: Sources/AdmiralChatSwiftUI/Resources/Assets/Symbols.xcassets
    outputs:
        templatePath: Templates/Images.stencil
        output: Sources/AdmiralChatSwiftUI/Assets/Symbols.swift
        params:
            publicAccess: 1
            allValues: 1
            enumName: AssetSymbol
