xcassets:
    inputs: AdmiralUIChatViewer/AdmiralUIChatViewer/Assets.xcassets
    outputs:
        templatePath: Templates/Images.stencil
        output: AdmiralUIChatViewer/AdmiralUIChatViewer/Resources/Assets.swift
        params:
            publicAccess: 1
            allValues: 1
            enumName: Assets
